---

- name: CentOS 8 configuration for Document Management
  hosts: localhost
  remote_user: root

  vars:
    appgroupname: imaging
    powertoolsreponame: CentOSStreamPowerTools
    ansible_python_interpreter: /usr/bin/python3.6
    overlay: https://github.com/BlacksilverConsulting/ImgOverlay/raw/main/var/imaging/resources

  handlers:
  - name: Restart FTP server
    service:
      name: vsftpd
      enabled: yes
      state: restarted

  tasks:
  - name: Create application group
    group:
      name: "{{ appgroupname }}"
      state: present

  - name: Create application users
    user:
      name: "{{ item }}"
      group: "{{ appgroupname }}"
    loop:
    - listener
    - dbmaint
    - mailer

  - name: Create application FTP accounts
    user:
      name: "{{ item.split(':')[0] }}"
      group: "{{ appgroupname }}"
      password: "{{ item.split(':')[1] }}"
      update_password: always
    loop:
    - 'barcode:$6$mysecretsalt$B1Sq0CjQnI4Y5M.ii2x7kI88/ERDXVyH1Z6JLenQaav7u6qDDnMjZexpCId77bC0SxjyUk1KqYf9sGXRttc4g.'
    - 'inqueue:$6$mysecretsalt$h9Qe0SkCC9h4tcMSRMRNqij7QsMP0o6jQn4JvlOdQJLK6fULfK1GgCkpd1CmER13aDwEgpqrA04s0/rr17Krh/'
    - 'invoice:$6$mysecretsalt$Qc.Fz0ZYIfSjCd.TO00BXXCZkGFOPgpCsl3c2nM7KPKi9yPzQT62.VhCpWPot/TQS7C3tDIHHCAxS54o24e0F/'
    - 'pages:$6$mysecretsalt$XV230BH4czvgKn8KcSW0wWUJVxinBqAbAi2XBTiJTTk5FjVv8ItZ4w9EMRmLdNfoGNzWdHugqPYB.gJYvv5iP.'
    - 'peoplenet:$6$mysecretsalt$mJ8RHipTJVhNyEmCexor4HTxNrcimKwOlCo8qpuX5UDe9HryH7qf10rvz1z5tLWulk8HS04/ROdPNxWpDUiK0.'
    - 'qc:$6$mysecretsalt$mJ8RHipTJVhNyEmCexor4HTxNrcimKwOlCo8qpuX5UDe9HryH7qf10rvz1z5tLWulk8HS04/ROdPNxWpDUiK0.'
    - 'scanner:$6$mysecretsalt$72YAmKvuS9HRllA6nWWV4JR.D54TrkIMrv3y3zZzdwHDg2ndAZu9z2veyGJgsl8op/CmzPRJEndLRVkWSzdSO.'
    - 'templates:$6$mysecretsalt$6TRIJ6gQhES4dFSHvGfzF0aDTW21Y6lVs.pHnT.rx9OZr8kVmADRwreqPxfFtVJR5z8HkGmJUN.60blLWXanR/'

# BEGIN POSTGRESQL SECTION
  - name: Create application-specific PostgreSQL users
    community.postgresql.postgresql_user:
      name: "{{ item }}"
      # We intentionally do not specify a password here
    loop:
    - 'dbmaint'
    - 'apache'
    - 'listener'
    - 'root'
    - 'backup'
    - 'mailer'
    become: yes
    become_user: postgres

  - name: Add systemd service alias for PostgreSQL 14
    # This is needed for application-specific automation
    #  that expects `service postgresql stop` to work
    file:
      src: /usr/lib/systemd/system/postgresql-14.service
      state: link
      path: /usr/lib/systemd/system/postgresql.service

  - name: Create /var/lib/pgsql/data symlink
    # This is needed for sysupdate.pl to complete
    file:
      state: link
      src: /var/lib/pgsql/14/data
      path: /var/lib/pgsql/data

  - name: Create fake init.d file
    # This is required for 2005091601 to work correctly.
    file:
      path: /etc/rc.d/init.d/postgresql
      state: touch
      modification_time: preserve
      access_time: preserve

# END POSTGRESQL SECTION

  - name: Create /etc/mail directory
    file:
      path: /etc/mail
      state: directory
      owner: mail
      group: mail

  - name: Add 'listener' to sendmail trusted users
    lineinfile:
      path: /etc/mail/trusted-users
      create: yes
      owner: mail
      group: mail
      line: 'listener'

  - name: Provide /etc/init.d for applications that reuiqre it
    file:
      state: link
      src: /etc/rc.d/init.d
      path: /etc/init.d

  - name: Install required groups
    yum:
      name:
      - "@smb-server"
      - "@web-server"
      state: present

  - name: Install additional packages
    yum:
      state: latest
      name:
      - 'expat'
      - 'expat-devel'
      - 'ncftp'
      - 'ncurses-devel'
      - 'openssl-devel'
      - 'zlib-devel'
      - 'sendmail'
      - 'sendmail-cf'
      - 'vsftpd'
      - 'foomatic-db'
      - 'ImageMagick-perl'
      - 'ImageMagick'
      - 'samba'
      - 'samba-client'
      - 'cifs-utils'
      - 'httpd'
      - 'perl-App-cpanminus'
      - 'perl-IO-CaptureOutput'
      - 'perl-URI-Encode'
      - 'perl-Class-Std'
      - 'perl-IO-Compress'
      - 'perl-Date-Manip'
      - 'perl-XML-Simple'
      - 'perl-Archive-Zip'
      - 'perl-XML-XPath'
      - 'perl-Compress-Raw-Zlib'
      - 'perl-Term-ReadLine-Gnu'
      - 'perl-LWP-Protocol-https'
      - 'perl-JSON-PP'
      - 'perl-String-ShellQuote'
      - 'perl-CGI'
      - 'perl-Parse-RecDescent'
      - 'perl-DBD-Pg'
      - 'foomatic'
      - 'freetds'
      - 'freetds-devel'

  - name: Configure required services to start automatically
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
    - cups
    - httpd
    - nmb
    - sendmail
    - smb
    - vsftpd

  - name: Configure FTP server
    ini_file:
      path: /etc/vsftpd.conf
      section: null
      no_extra_spaces: yes
      option: "{{ item.split(':')[0] }}"
      value: "{{ item.split(':')[1] }}"
    loop:
    - local_umask:002
    - write_enable:yes
    notify: Restart FTP server

  - name: Add firewall rules
    firewalld:
      service: "{{ item }}"
      state: enabled
      immediate: yes
      permanent: yes
    loop:
    - ftp
    - http

  - name: Change ImageMagick policy XML 1/4
    xml:
      path: "/etc/ImageMagick-6/policy.xml"
      xpath: '/policymap/policy[@pattern="TEXT"]'
      state: present
      attribute: domain
      value: coder
      pretty_print: yes

  - name: Change ImageMagick policy XML 2/4
    xml:
      path: "/etc/ImageMagick-6/policy.xml"
      xpath: '/policymap/policy[@pattern="TEXT"]'
      state: present
      attribute: rights
      value: read
      pretty_print: yes

  - name: Change ImageMagick policy XML 3/4
    xml:
      path: "/etc/ImageMagick-6/policy.xml"
      xpath: '/policymap/policy[@pattern="LABEL"]'
      state: present
      attribute: domain
      value: coder
      pretty_print: yes

  - name: Change ImageMagick policy XML 4/4
    xml:
      path: "/etc/ImageMagick-6/policy.xml"
      xpath: '/policymap/policy[@pattern="LABEL"]'
      state: present
      attribute: rights
      value: read
      pretty_print: yes

# BEGIN POWERTOOLS SECTION

  - name: Install RPM signing key for PowerTools
    rpm_key:
      key: http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-Official
      state: present

  - name: Configure CentOS PowerTools repository
    yum_repository:
      name: "{{ powertoolsreponame }}"
      description: PowerTools from CentOS Stream 8
      enabled: true
      gpgcheck: true
      mirrorlist: http://mirrorlist.centos.org/?release=$stream&arch=$basearch&repo=PowerTools&infra=$infra
      state: present

  - name: Install packages from PowerTools
    yum:
      name:
      - gperf.x86_64
      - gsm-devel.x86_64
      - jbigkit-devel.x86_64
#      - latex2html.x86_64
      - lcms2-devel.x86_64
      - libtiff-tools.x86_64
#      - libv41-devel.x86_64
      - lockdev-devel.x86_64
      - perl-IPC-Run3.noarch
      - perl-Unicode-EastAsianWidth.noarch
      - pygobject3-devel.x86_64
      - sharutils.x86_64
#      - text2html.noarch
      - texinfo.x86_64
      - texinfo-tex.x86_64
      state: latest
      enablerepo: "{{ powertoolsreponame }}"

# END POSTGRESQL SECTION


  - name: install cpan modules
    cpanm:
      name: "{{ item }}"
      notest: yes
    environment:
      SYBASE: '/usr'
    loop:
    - 'Any::Daemon'
    - 'Class::Std::Fast'
    - 'DBD::Sybase'
    - 'IO::Pty'
    - 'IO::Tty'
    - 'List::MoreUtils'
    - 'Log::LogLite'
    - 'Log::Report'
    - 'Mail::POP3Client'
    - 'MIME::Lite'
    - 'Net::Azure::StorageClient'
    - 'Net::FTP::Common'
    - 'Net::LDAP'
    - 'Net::SFTP::Foreign'
    - 'Params::Validate'
    - 'Params::Validate::Checks'
    - 'SOAP::WSDL'
    - 'Term::ReadKey'
    - 'Test::Pod'
    - 'URI::sftp'
    - 'XML::Compile::SOAP::Daemon::AnyDaemon'
    - 'XML::Tidy'

  - name: Install APF 3.02
    unarchive:
      dest:       /var/www/html
      creates:    /var/www/html/apf_3.02_sdk
      src:        "{{ overlay }}/packages/apf_3.02_sdk.zip"
      remote_src: yes

  - name: Install APF Skins
    unarchive:
      dest:       /var/www/html
      creates:    /var/www/html/apf_skin
      src:        "{{ overlay }}/packages/apf_skin.zip"
      remote_src: yes

  - name: Install YUI
    unarchive:
      dest:       /var/www/html
      creates:    /var/www/html/yui
      src:        "{{ overlay }}/packages/yui-2.9.0.tgz"
      remote_src: yes

  - name: Install imaging-listener service definition
    get_url:
      url: "{{ overlay }}/services/imaging-listener.service"
      owner: "root"
      group: "root"
      mode: "0644"
      dest: "/usr/lib/systemd/system"

  - name: Enable imaging-listener service
    service:
      name: imaging-listener
      enabled: yes

  - name: Install imaging-cleanup service definition
    get_url:
      url: "{{ overlay }}/services/imaging-cleanup.service"
      owner: "root"
      group: "root"
      mode: "0644"
      dest: "/usr/lib/systemd/system"

  - name: Enable imaging-cleanup service
    service:
      name: imaging-cleanup
      enabled: yes

...